language: python
sudo: required
python:
   - 3.5

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q
    - set -x; sudo apt-get install -y -q openmpi-bin libopenmpi-dev

    # Use miniconda to setup pytorch
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

install:
   - pip install --upgrade pip
   - pip install --progress-bar off -r requirements.txt
   - pip install --progress-bar off --editable .
   - pip install --progress-bar off nose
   - conda install pytorch torchvision -c pytorch
#   - pip install --progress-bar off torch
script:
   - nosetests tests -s
